EVerest/everest-admin-panel

.github/workflows/package.yaml

Signed-off-by: aw <aw@pionix.de>

Initial github action

---

src/components/EvModuleInfo.vue
tsconfig.json

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #19
* #18
* #17
* #16
* #15
* __->__ #14

fix: button styling

---

src/router/index.ts

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* #19
* #18
* #17
* __->__ #16
* #15
* #14

feat(routing): auto-redirect to config-page

---

src/components/EvModuleInfo.vue
src/components/IconButtonWithTooltip.vue

Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #19
* #18
* #17
* #16
* #15
* #14

fix(EvModuleInfo): close buttons

---

pnpm-lock.yaml

commit-id:74605370
---
**Stack**:
- #44
- #43
- #46 ⬅

ci(pnpm-lock): executed pnpm install to fix diverged pnpm-lock

---

package.json
pnpm-lock.yaml
public/img/icons/everest_lf_logo_white.svg
src/components/EvConfigCanvas.vue
src/main.scss
src/main.ts
src/modules/evconf_konva/config_stage.ts
src/modules/evconf_konva/views/constants.ts
src/modules/evconf_konva/views/module.ts
src/modules/evconf_konva/views/shapes/terminal.ts
src/pages/MainPanel.vue
src/plugins/vuetify.ts

closes #76
commit-id:dee925ae
---
**Stack**:
- #86
- #83 ⬅
- #78

fix(load-config): deal with non-existing terminals in config

---

package.json
pnpm-lock.yaml
src/components/EvConfigCanvas.vue
src/main.scss
src/modules/evconf_konva/config_stage.ts
src/pages/ConfigPage.vue

Closes #30
---
**Stack**:
- #106
- #104
- #102
- #99
- #98
- #97
- #95 ⬅

feat(ConfigPage): allow to dynamically adjust ui element sizes

---

.github/workflows/package-and-deploy.yml
package.json
pnpm-lock.yaml
src/components/ConfigPreview.vue
src/components/EvConfigCanvas.vue
src/plugins/index.ts

Closes #105
commit-id:8c155f5f
---
**Stack**:
- #106 ⬅
- #104
- #102

feat(config-preview): copy & download-button

---

src/modules/evconf_konva/views/module.ts

fix(config_stage): blurry modules

---

.eslintrc.cjs
.github/workflows/checks.yml
.gitignore
.licenserc.yaml
index.html
public/favicon/browserconfig.xml
src/App.vue
src/components/ConfigPreview.vue
src/components/EvConfigCanvas.vue
src/components/EvDialog.vue
src/components/EvModuleInfo.vue
src/components/EvModuleList.vue
src/components/IconButtonWithTooltip.vue
src/main.scss
src/modules/evbc/rpc/abstractRpcIssuer.ts
src/modules/evbc/rpc/loopbackRpcIssuer.ts
src/modules/evbc/rpc/websocketRpcIssuer.ts
src/pages/ConfigPage.vue
src/pages/ConnectPage.vue
src/pages/MainPanel.vue

I added a license header check, so that we don't forget adding a license header to files.

ci(license-header-check): added

---

renovate.json5

ci(renovate): added

---

.github/workflows/shrinkwrap.yml

---
**Stack**:
- #111
- #110 ⬅

ci(shrinkwrap): added generator

---

THIRD_PARTY.md
package.json
pnpm-lock.yaml

---
**Stack**:
- #111 ⬅
- #110

chore(deps): removed unneeded vue-class-component + vue-property-decorator dependency

---

build-tools/fetch-schemas-plugin.ts
cypress/e2e/config-management.cy.ts
schemas.config.ts
src/components/CreateConfig.vue
src/utils.test.ts
src/utils.ts

They were missing because the pipeline didn't run correctly on PRs. See #165
---
**Stack**:
- #165
- #167 ⬅

chore(license-headers): added to a few files

---

.github/workflows/checks.yml

---
**Stack**:
- #165 ⬅
- #167

ci(license-scanner): didn't run on PRs correctly, now does

---

.github/workflows/lint.yml

ci(eslint): added lint job

---

.github/workflows/checks.yml
.github/workflows/deploy.yml
.github/workflows/e2e-tests.yml
.github/workflows/lint.yml
.github/workflows/package.yml
.github/workflows/unit-tests.yml

ci: execute on prs against all branches for graphite compatibility

---

tsconfig.json
tsconfig.node.json

chore(tsconfig): switch to moduleResolution bundler

---

.github/workflows/lint.yml

ci(vue-tsc): added job to run vue-tsc to validate strict types

---

schemas.config.ts

This should resolve all issues caused by changed schemas in everest-framework.

chore: update schemas to latest everest-framework release

---

src/main.ts
src/modules/evconf_konva/config_stage.ts

now when moving the mousewheel up config items get larger (which feels natural)

fix unnatural scrolldirection

---

src/store/errorStore.ts

Signed-off-by: 12fab4 <mailfuerfabian@web.de>

chore: made license-eye happy
